### ISSUE TITLE
Extend the repo readme

### ISSUE THREAD

**Issue by CoachBirgit** [impress-org/give-sofort#1]
Make the readme nice and educational

ToDo:

- [ ] Add credits 

- [ ] Add screenshots

- [ ] Add description about the installation, settings, and usage of the plugin

- [ ] Add description about the project settings on Sofort.com and where to find the config key

**Comment by DevinWalker** [comment]
Since this is a private repo we're going to rely on the docs on givewp.com and just use readme as basic content.
