### ISSUE TITLE
Keep getting Error: 401:Unauthorized

### ISSUE THREAD

**Issue by n1smo** [impress-org/give-sofort#5]
Hi,

thank you for this plugin.
But when i try to use it, im alway getting on a blank page with the error "Error: 401:Unauthorized" once i click on donate.

I entered a valid config key and my sofort.com account/project is activated also.

Any ideas?

Kind Regards
n

**Comment by mahype** [comment]
Hi!

Which URL do you see at the browser in the moment you see the 401 error?

Greetings,

Sven

**Comment by n1smo** [comment]
Its the url of the page the form was on with GET variable "?payment-mode=sofort"

Like, www.mypage.com/donations/?payment-mode=sofort

**Comment by CoachBirgit** [comment]
Hi @n1smo 

Thanks for bringing up this issue to our attention. Please replace following line: 

https://github.com/CoachBirgit/give-sofort/blob/master/vendor/class-sofort-payment.php#L121

from
`$api_config_key = give_get_option( 'sofort_config_key' );`

to
`$api_config_key = give_get_option( 'live_sofort_config_key' );`

as quick fix. 

Please confirm if it does work for you. I'll push an bugfix as soon as possible to this repo. 

Kind regards,
Birgit

**Comment by n1smo** [comment]
That works, thanks !
